import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster"
  
import { Poppins } from 'next/font/google'
 
const poppins = Poppins({
  weight:  [
    '100',  // Thin
    '200',  // Extra Light
    '300',  // Light
    '400',  // Regular
    '500',  // Medium
    '600',  // Semi Bold
    '700',  // Bold
    '800',  // Extra Bold
    '900'   // Black
  ],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Fintech",
  description: "Generated by Prabisha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />

        </ThemeProvider>
      </body>
    </html>
  );
}
